export const UPDATE_FLASH = 'UPDATE_FLASH'

export const CREATE_STACK = 'CREATE_STACK'
export const UPDATE_STACK = 'UPDATE_STACK'
export const DELETE_STACK = 'DELETE_STACK'
export const DESTROY_STACK = 'DESTROY_STACK'
export const CLEAR_ALL_STACK = 'CLEAR_ALL_STACK'

export const CART_UPDATE_CARTS = 'CART_UPDATE_CARTS'
export const CART_UPDATE_PAYLOAD = 'CART_UPDATE_PAYLOAD'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const SCHEDULE_UPDATE_PAYLOAD = 'SCHEDULE_UPDATE_PAYLOAD'
export const SCHEDULE_RESET_PAYLOAD = 'SCHEDULE_RESET_PAYLOAD'
export const SCHEDULE_UPDATE_PRODUCT = 'SCHEDULE_UPDATE_PRODUCT'

export const SEARCH_UPDATE_PAYLOAD = 'SEARCH_UPDATE_PAYLOAD'
export const SEARCH_UPDATE_QUERY = 'SEARCH_UPDATE_QUERY'
export const SEARCH_REMOVE_HISTORY = 'SEARCH_REMOVE_HISTORY'

export const RECENTLY_COLLECTION_UPDATE_PAYLOAD = 'RECENTLY_COLLECTION_UPDATE_PAYLOAD'

export const UPDATE_STORE = 'UPDATE_STORE'
