# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  balance    :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  DEFAULT_VALUES = {
    balance: 1000
  }
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :with_balance, -> { where("balance > 0").take }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def update_new_balance(profit)
    update(balance: self.balance + profit)
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
